name: MERGE

on:
  push:
   branches:
    - main

jobs:
  build_and_release:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm ci

      - name: Linting
        run: npm run lint

      - name: Unit test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Prepare release
        run: |
          git config user.email "mytradables@gmail.com"
          git config user.name "mt-actions"
          npm run release

      - name: Git push changes
        run: git push --follow-tags origin main

  publish-gpr:
    needs: build_and_release
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
